#pragma once

enum e_effects
{
	ef_bone_merge = 0x001,
	ef_bright_light = 0x002,
	ef_dimlight = 0x004,
	ef_no_interp = 0x008,
	ef_no_shadow = 0x010,
	ef_no_draw = 0x020,
	ef_no_receive_shadow = 0x040,
	ef_bone_merge_fastcull = 0x080,
	ef_item_blink = 0x100,
	ef_parent_animates = 0x200,
	ef_marked_for_fast_reflection = 0x400,
	ef_no_shadow_depth = 0x800,
	ef_shadow_depth_no_cache = 0x1000,
	ef_no_flash_light = 0x2000,
	ef_no_csm = 0x4000,
	ef_max_bits = 15
};

enum e_buttons
{
	in_attack = 1 << 0,
	in_jump = 1 << 1,
	in_duck = 1 << 2,
	in_forward = 1 << 3,
	in_back = 1 << 4,
	in_use = 1 << 5,
	in_cancel = 1 << 6,
	in_left = 1 << 7,
	in_right = 1 << 8,
	in_moveleft = 1 << 9,
	in_moveright = 1 << 10,
	in_attack2 = 1 << 11,
	in_run = 1 << 12,
	in_reload = 1 << 13,
	in_alt1 = 1 << 14,
	in_alt2 = 1 << 15,
	in_score = 1 << 16,
	in_speed = 1 << 17,
	in_walk = 1 << 18,
	in_zoom = 1 << 19,
	in_weapon1 = 1 << 20,
	in_weapon2 = 1 << 21,
	in_bullrush = 1 << 22,
	in_grenade1 = 1 << 23,
	in_grenade2 = 1 << 24,
	in_lookspin = 1 << 25
};

enum e_frame_stage
{
	frame_undefined = -1,
	frame_start,
	frame_net_update_start,
	frame_net_update_postdataupdate_start,
	frame_net_update_postdataupdate_end,
	frame_net_update_end,
	frame_render_start,
	frame_render_end
};

enum e_chars
{
	char_tex_antlion = 'a',
	char_tex_bloodyflesh = 'b',
	char_tex_concrete = 'c',
	char_tex_dirt = 'd',
	char_tex_eggshell = 'e',
	char_tex_flesh = 'f',
	char_tex_grate = 'g',
	char_tex_alienflesh = 'h',
	char_tex_clip = 'i',
	char_tex_plastic = 'l',
	char_tex_metal = 'm',
	char_tex_sand = 'n',
	char_tex_foliage = 'o',
	char_tex_computer = 'p',
	char_tex_slosh = 's',
	char_tex_tile = 't',
	char_tex_cardboard = 'u',
	char_tex_vent = 'v',
	char_tex_wood = 'w',
	char_tex_glass = 'y',
	char_tex_warpshield = 'z',
};

enum e_team_id
{
	team_unassigned = 0,
	team_spectator,
	team_tt,
	team_ct
};

enum e_life_state
{
	life_alive = 0,
	life_dying = 1,
	life_dead = 2,
	max_life_state
};

enum e_move_type
{
	move_type_none = 0,
	move_type_isometric,
	move_type_walk,
	move_type_step,
	move_type_fly,
	move_type_fly_gravity,
	move_type_vphysics,
	move_type_push,
	move_type_noclip,
	move_type_ladder,
	move_type_ob_server,
	move_type_custom,
	move_type_last = move_type_custom,
	move_type_max_bits = 4
};

enum e_flags
{
	fl_on_ground = 1 << 0,
	fl_ducking = 1 << 1,
	fl_anim_ducking = 1 << 2,
	fl_water_jump = 1 << 3,
	fl_on_train = 1 << 4,
	fl_in_rain = 1 << 5,
	fl_frozen = 1 << 6,
	fl_at_controls = 1 << 7,
	fl_client = 1 << 8,
	fl_fake_client = 1 << 9,
	fl_in_water = 1 << 10,
	fl_fly = 1 << 11,
	fl_swim = 1 << 12,
	fl_conveyor = 1 << 13,
	fl_npc = 1 << 14,
	fl_god_mode = 1 << 15,
	fl_no_target = 1 << 16,
	fl_aim_target = 1 << 17,
	fl_partial_ground = 1 << 18,
	fl_static_prop = 1 << 19,
	fl_graphed = 1 << 20,
	fl_grenade = 1 << 21,
	fl_step_movement = 1 << 22,
	fl_dont_touch = 1 << 23,
	fl_base_velocity = 1 << 24,
	fl_world_brush = 1 << 25,
	fl_object = 1 << 26,
	fl_kill_me = 1 << 27,
	fl_on_fire = 1 << 28,
	fl_dissolving = 1 << 29,
	fl_trans_ragdoll = 1 << 30,
	fl_unblockable_by_player = 1 << 31
};

enum e_collision_group
{
	collision_group_none = 0,
	collision_group_debris,						// collides with nothing but world and static stuff
	collision_group_debris_trigger,				// same as debris, but hits triggers
	collision_group_interactive_debris,			// collides with everything except other interactive debris or debris
	collision_group_interactive,				// collides with everything except interactive debris or debris
	collision_group_player,
	collision_group_breakable_glass,
	collision_group_vehicle,
	collision_group_player_movement,			// for HL2, same as Collision_Group_Player, for / TF2, this filters out other players and CBaseObjects
	collision_group_npc,						// generic NPC group
	collision_group_in_vehicle,					// for any entity inside a vehicle
	collision_group_weapon,						// for any weapons that need collision detection
	collision_group_vehicle_clip,				// vehicle clip brush to restrict vehicle movement
	collision_group_projectile,					// projectiles!
	collision_group_door_blocker,				// blocks entities not permitted to get near moving doors
	collision_group_passable_door,				// doors that the player shouldn't collide with
	collision_group_dissolving,					// things that are dissolving are in this group
	collision_group_pushaway,					// nonsolid on client and server, pushaway in player code
	collision_group_npc_actor,					// used so NPCs in scripts ignore the player.
	collision_group_npc_scripted,				// used for NPCs in scripts that should not collide with each other
	collision_group_pz_clip,
	collision_group_debris_block_projectile,	// only collides with bullets
	last_shared_collision_group
};

enum e_idx : short
{
	weapon_none = 0,
	weapon_deagle,
	weapon_elite,
	weapon_fiveseven,
	weapon_glock,
	weapon_ak47 = 7,
	weapon_aug,
	weapon_awp,
	weapon_famas,
	weapon_g3sg1,
	weapon_galilar = 13,
	weapon_m249,
	weapon_m4a1 = 16,
	weapon_mac10,
	weapon_p90 = 19,
	weapon_mp5sd = 23,
	weapon_ump45,
	weapon_xm1014,
	weapon_bizon,
	weapon_mag7,
	weapon_negev,
	weapon_sawedoff,
	weapon_tec9,
	weapon_taser,
	weapon_hkp2000,
	weapon_mp7,
	weapon_mp9,
	weapon_nova,
	weapon_p250,
	weapon_shield,
	weapon_scar20,
	weapon_sg553,
	weapon_ssg08,
	weapon_knifegg,
	weapon_knife,
	weapon_flashbang,
	weapon_hegrenade,
	weapon_smokegrenade,
	weapon_molotov,
	weapon_decoy,
	weapon_incgrenade,
	weapon_c4,
	weapon_healthshot = 57,
	weapon_knife_t = 59,
	weapon_m4a1_silencer,
	weapon_usp_silencer,
	weapon_cz75a = 63,
	weapon_revolver,
	weapon_tagrenade = 68,
	weapon_fists,
	weapon_breachcharge,
	weapon_tablet = 72,
	weapon_melee = 74,
	weapon_axe,
	weapon_hammer,
	weapon_spanner = 78,
	weapon_knife_ghost = 80,
	weapon_firebomb,
	weapon_diversion,
	weapon_frag_grenade,
	weapon_snowball,
	weapon_bumpmine,
	weapon_knife_bayonet = 500,
	weapon_knife_css = 503,
	weapon_knife_flip = 505,
	weapon_knife_gut,
	weapon_knife_karambit,
	weapon_knife_m9_bayonet,
	weapon_knife_tactical,
	weapon_knife_falchion = 512,
	weapon_knife_survival_bowie = 514,
	weapon_knife_butterfly,
	weapon_knife_push,
	weapon_knife_cord,
	weapon_knife_canis,
	weapon_knife_ursus = 519,
	weapon_knife_gypsy_jackknife,
	weapon_knife_outdoor,
	weapon_knife_stiletto = 522,
	weapon_knife_widowmaker,
	weapon_knife_skeleton = 525,
	studded_brokenfang_gloves = 4725,
	glove_studded_bloodhound = 5027,
	glove_t_side,
	glove_ct_side,
	glove_sporty,
	glove_slick,
	glove_leather_wrap,
	glove_motorcycle,
	glove_specialist,
	glove_hydra,
};

enum e_weapon_type 
{
	weapon_type_knife = 0,
	weapon_type_pistol,
	weapon_type_submachinegun,
	weapon_type_rifle,
	weapon_type_shotgun,
	weapon_type_sniper_rifle,
	weapon_type_machinegun,
	weapon_type_c4,
	weapon_type_placeholder,
	weapon_type_grenade,
	weapon_type_unknown
};

enum { max_inferno_fires = 100 };

enum e_class_id 
{
	class_id_ai_base_npc = 0,
	class_id_c_ak47,
	class_id_base_animating,
	class_id_base_animating_overlay,
	class_id_base_attributable_item,
	class_id_base_button,
	class_id_base_combat_character,
	class_id_base_combat_weapon,
	class_id_base_cs_grenade,
	class_id_base_cs_grenade_projectile,
	class_id_base_door,
	class_id_base_entity,
	class_id_base_flex,
	class_id_base_grenade,
	class_id_base_particle_entity,
	class_id_base_player,
	class_id_base_prop_door,
	class_id_base_team_objective_resource,
	class_id_base_temp_entity,
	class_id_base_toggle,
	class_id_base_trigger,
	class_id_base_view_model,
	class_id_base_physics_trigger,
	class_id_base_weapon_world_model,
	class_id_beam,
	class_id_beam_spot_light,
	class_id_bone_follower,
	class_id_br_c4_target,
	class_id_breach_charge,
	class_id_breach_charge_projectile,
	class_id_breakable_prop,
	class_id_breakable_surface,
	class_id_bump_mine,
	class_id_bump_mine_projectile,
	class_id_c_c4,
	class_id_cascade_light,
	class_id_chicken,
	class_id_color_correction,
	class_id_color_correctionv_olume,
	class_id_cs_game_rules_proxy,
	class_id_cs_player,
	class_id_cs_player_resource,
	class_id_cs_ragdoll,
	class_id_cs_team,
	class_id_danger_zone,
	class_id_danger_zone_controller,
	class_id_deagle,
	class_id_decoy_grenade,
	class_id_decoy_projectile,
	class_id_drone,
	class_id_drone_gun,
	class_id_dynamic_light,
	class_id_dynamic_prop,
	class_id_econ_entity,
	class_id_econ_wearable,
	class_id_embers,
	class_id_entity_dissolve,
	class_id_entity_flame,
	class_id_entity_freezing,
	class_id_entity_particletrail,
	class_id_env_ambient_light,
	class_id_env_detail_controller,
	class_id_env_dof_controller,
	class_id_env_gas_canister,
	class_id_env_particle_script,
	class_id_env_projected_texture,
	class_id_env_quadratic_beam,
	class_id_env_screen_effect,
	class_id_env_screen_overlay,
	class_id_env_tonemap_controller,
	class_id_env_wind,
	class_id_fe_player_decal,
	class_id_fire_cracker_blast,
	class_id_fire_smoke,
	class_id_fire_trail,
	class_id_fish,
	class_id_fists,
	class_id_flashbang,
	class_id_fog_controller,
	class_id_footstep_control,
	class_id_func_dust,
	class_id_func_lod,
	class_id_func_area_portal_window,
	class_id_func_brush,
	class_id_func_conveyor,
	class_id_func_ladder,
	class_id_func_monitor,
	class_id_func_move_linear,
	class_id_func_occluder,
	class_id_func_reflective_glass,
	class_id_func_rotating,
	class_id_func_smoke_volume,
	class_id_func_track_train,
	class_id_game_rules_proxy,
	class_id_grass_burn,
	class_id_handle_test,
	class_id_he_grenade,
	class_id_hostage,
	class_id_hostage_carriable_prop,
	class_id_incendiary_grenade,
	class_id_inferno,
	class_id_info_ladder_dismount,
	class_id_info_map_region,
	class_id_info_overlay_accessor,
	class_id_item_healthshot,
	class_id_item_cash,
	class_id_item_dogtags,
	class_id_knife,
	class_id_knife_gg,
	class_id_light_glow,
	class_id_map_veto_pick_controller,
	class_id_material_modify_control,
	class_id_melee,
	class_id_molotov_grenade,
	class_id_molotov_projectile,
	class_id_movie_display,
	class_id_paradrop_chopper,
	class_id_particle_fire,
	class_id_particle_performance_monitor,
	class_id_particle_system,
	class_id_phys_box,
	class_id_phys_box_multiplayer,
	class_id_physics_prop,
	class_id_physics_prop_multiplayer,
	class_id_phys_magnet,
	class_id_phys_prop_ammo_box,
	class_id_phys_prop_loot_crate,
	class_id_phys_prop_radar_jammer,
	class_id_phys_prop_weapon_upgrade,
	class_id_planted_c4,
	class_id_plasma,
	class_id_player_ping,
	class_id_player_resource,
	class_id_point_camera,
	class_id_point_commentarynode,
	class_id_point_worldtext,
	class_id_pose_controller,
	class_id_post_process_controller,
	class_id_precipitation,
	class_id_precipitation_blocker,
	class_id_predicted_view_model,
	class_id_prop_hallucination,
	class_id_prop_counter,
	class_id_prop_door_rotating,
	class_id_prop_jeep,
	class_id_prop_vehicle_driveable,
	class_id_ragdoll_manager,
	class_id_ragdoll_prop,
	class_id_ragdoll_prop_attached,
	class_id_rope_key_frame,
	class_id_scar17,
	class_id_scene_entity,
	class_id_sensor_grenade,
	class_id_sensor_grenade_projectile,
	class_id_shadow_control,
	class_id_slideshow_display,
	class_id_smoke_grenade,
	class_id_smoke_grenade_projectile,
	class_id_smoke_stack,
	class_id_snowball,
	class_id_snowball_pile,
	class_id_snowball_projectile,
	class_id_spatial_entity,
	class_id_spotlight_end,
	class_id_sprite,
	class_id_sprite_oriented,
	class_id_sprite_trail,
	class_id_statue_prop,
	class_id_steam_jet,
	class_id_sun,
	class_id_sun_light_shadow_control,
	class_id_survival_spawn_chopper,
	class_id_tablet,
	class_id_team,
	class_id_team_play_round_based_rules_proxy,
	class_id_te_armor_ricochet,
	class_id_te_base_beam,
	class_id_te_beam_ent_point,
	class_id_te_beam_ents,
	class_id_te_beam_follow,
	class_id_te_beam_laser,
	class_id_te_beam_points,
	class_id_te_beam_ring,
	class_id_te_beam_ring_point,
	class_id_te_beam_spline,
	class_id_te_blood_sprite,
	class_id_te_blood_stream,
	class_id_te_break_model,
	class_id_te_bsp_decal,
	class_id_te_bubbles,
	class_id_te_bubble_trail,
	class_id_te_client_projectile,
	class_id_te_decal,
	class_id_te_dust,
	class_id_te_dynamic_light,
	class_id_te_effect_dispatch,
	class_id_te_energy_splash,
	class_id_te_explosion,
	class_id_te_fire_bullets,
	class_id_te_fizz,
	class_id_te_foot_print_decal,
	class_id_te_foundry_helpers,
	class_id_te_gauss_explosion,
	class_id_te_glow_sprite,
	class_id_te_impact,
	class_id_te_kill_player_attachments,
	class_id_te_large_funnel,
	class_id_te_metal_sparks,
	class_id_te_muzzle_flash,
	class_id_te_particle_system,
	class_id_te_physics_prop,
	class_id_te_plant_bomb,
	class_id_te_player_animevent,
	class_id_te_player_decal,
	class_id_te_projected_decal,
	class_id_te_radio_icon,
	class_id_te_shatter_surface,
	class_id_te_show_line,
	class_id_te_sla,
	class_id_te_smoke,
	class_id_te_sparks,
	class_id_te_sprite,
	class_id_te_sprite_spray,
	class_id_test_proxytoggle_networkable,
	class_id_testtraceline,
	class_id_teworlddecal,
	class_id_trigger_player_movement,
	class_id_trigger_sound_operator,
	class_id_vgui_screen,
	class_id_vote_controller,
	class_id_water_bullet,
	class_id_water_bod_control,
	class_id_weapon_aug,
	class_id_weapon_awp,
	class_id_weapon_base_item,
	class_id_weapon_bizon,
	class_id_weapon_cs_base,
	class_id_weapon_cs_base_gun,
	class_id_weapon_cycler,
	class_id_weapon_elite,
	class_id_weapon_famas,
	class_id_weapon_five_seven,
	class_id_weapon_g3sg1,
	class_id_weapon_galil,
	class_id_weapon_galil_ar,
	class_id_weapon_glock,
	class_id_weapon_hkp2000,
	class_id_weapon_m249,
	class_id_weapon_m3,
	class_id_weapon_m4a1,
	class_id_weapon_mac10,
	class_id_weapon_mag7,
	class_id_weapon_mp5_navy,
	class_id_weapon_mp7,
	class_id_weapon_mp9,
	class_id_weapon_negev,
	class_id_weapon_nova,
	class_id_weapon_p228,
	class_id_weapon_p250,
	class_id_weapon_p90,
	class_id_weapon_sawedoff,
	class_id_weapon_scar20,
	class_id_weapon_scout,
	class_id_weapon_sg550,
	class_id_weapon_sg552,
	class_id_weapon_sg556,
	class_id_weapon_shield,
	class_id_weapon_ssg08,
	class_id_weapon_taser,
	class_id_weapon_tec9,
	class_id_weapon_tmp,
	class_id_weapon_ump45,
	class_id_weapon_usp,
	class_id_weapon_xm1014,
	class_id_weapon_zone_repulsor,
	class_id_world,
	class_id_world_vgui_text,
	class_id_dust_trail,
	class_id_movie_explosion,
	class_id_particle_smoke_grenade,
	class_id_rocket_trail,
	class_id_smoke_trail,
	class_id_spore_explosion,
	class_id_spore_trail
};

enum e_animationlayer
{
	animation_layer_aimmatrix = 0,
	animation_layer_weapon_action,
	animation_layer_weapon_action_recrouch,
	animation_layer_adjust,
	animation_layer_movement_jump_or_fall,
	animation_layer_movement_land_or_climb,
	animation_layer_movement_move,
	animation_layer_movement_strafechange,
	animation_layer_whole_body,
	animation_layer_flashed,
	animation_layer_flinch,
	animation_layer_aliveloop,
	animation_layer_lean,
	animation_layer_count,
};

enum e_activities : int {
	act_invalid = -1,
	act_reset = 0,
	act_idle = 1,
	act_transition = 2,
	act_cover = 3,
	act_cover_med = 4,
	act_cover_low = 5,
	act_walk = 6,
	act_walk_aim = 7,
	act_walk_crouch = 8,
	act_walk_crouch_aim = 9,
	act_run = 10,
	act_run_aim = 11,
	act_run_crouch = 12,
	act_run_crouch_aim = 13,
	act_run_protected = 14,
	act_script_custom_move = 15,
	act_range_attack1 = 16,
	act_range_attack2 = 17,
	act_range_attack1_low = 18,
	act_range_attack2_low = 19,
	act_diesimple = 20,
	act_diebackward = 21,
	act_dieforward = 22,
	act_dieviolent = 23,
	act_dieragdoll = 24,
	act_fly = 25,
	act_hover = 26,
	act_glide = 27,
	act_swim = 28,
	act_jump = 29,
	act_hop = 30,
	act_leap = 31,
	act_land = 32,
	act_climb_up = 33,
	act_climb_down = 34,
	act_climb_dismount = 35,
	act_shipladder_up = 36,
	act_shipladder_down = 37,
	act_strafe_left = 38,
	act_strafe_right = 39,
	act_roll_left = 40,
	act_roll_right = 41,
	act_turn_left = 42,
	act_turn_right = 43,
	act_crouch = 44,
	act_crouchidle = 45,
	act_stand = 46,
	act_use = 47,
	act_alien_burrow_idle = 48,
	act_alien_burrow_out = 49,
	act_signal1 = 50,
	act_signal2 = 51,
	act_signal3 = 52,
	act_signal_advance = 53,
	act_signal_forward = 54,
	act_signal_group = 55,
	act_signal_halt = 56,
	act_signal_left = 57,
	act_signal_right = 58,
	act_signal_takecover = 59,
	act_lookback_right = 60,
	act_lookback_left = 61,
	act_cower = 62,
	act_small_flinch = 63,
	act_big_flinch = 64,
	act_melee_attack1 = 65,
	act_melee_attack2 = 66,
	act_reload = 67,
	act_reload_start = 68,
	act_reload_finish = 69,
	act_reload_low = 70,
	act_arm = 71,
	act_disarm = 72,
	act_drop_weapon = 73,
	act_drop_weapon_shotgun = 74,
	act_pickup_ground = 75,
	act_pickup_rack = 76,
	act_idle_angry = 77,
	act_idle_relaxed = 78,
	act_idle_stimulated = 79,
	act_idle_agitated = 80,
	act_idle_stealth = 81,
	act_idle_hurt = 82,
	act_walk_relaxed = 83,
	act_walk_stimulated = 84,
	act_walk_agitated = 85,
	act_walk_stealth = 86,
	act_run_relaxed = 87,
	act_run_stimulated = 88,
	act_run_agitated = 89,
	act_run_stealth = 90,
	act_idle_aim_relaxed = 91,
	act_idle_aim_stimulated = 92,
	act_idle_aim_agitated = 93,
	act_idle_aim_stealth = 94,
	act_walk_aim_relaxed = 95,
	act_walk_aim_stimulated = 96,
	act_walk_aim_agitated = 97,
	act_walk_aim_stealth = 98,
	act_run_aim_relaxed = 99,
	act_run_aim_stimulated = 100,
	act_run_aim_agitated = 101,
	act_run_aim_stealth = 102,
	act_crouchidle_stimulated = 103,
	act_crouchidle_aim_stimulated = 104,
	act_crouchidle_agitated = 105,
	act_walk_hurt = 106,
	act_run_hurt = 107,
	act_special_attack1 = 108,
	act_special_attack2 = 109,
	act_combat_idle = 110,
	act_walk_scared = 111,
	act_run_scared = 112,
	act_victory_dance = 113,
	act_die_headshot = 114,
	act_die_chestshot = 115,
	act_die_gutshot = 116,
	act_die_backshot = 117,
	act_flinch_head = 118,
	act_flinch_chest = 119,
	act_flinch_stomach = 120,
	act_flinch_leftarm = 121,
	act_flinch_rightarm = 122,
	act_flinch_leftleg = 123,
	act_flinch_rightleg = 124,
	act_flinch_physics = 125,
	act_flinch_head_back = 126,
	act_flinch_head_left = 127,
	act_flinch_head_right = 128,
	act_flinch_chest_back = 129,
	act_flinch_stomach_back = 130,
	act_flinch_crouch_front = 131,
	act_flinch_crouch_back = 132,
	act_flinch_crouch_left = 133,
	act_flinch_crouch_right = 134,
	act_idle_on_fire = 135,
	act_walk_on_fire = 136,
	act_run_on_fire = 137,
	act_rappel_loop = 138,
	act_180_left = 139,
	act_180_right = 140,
	act_90_left = 141,
	act_90_right = 142,
	act_step_left = 143,
	act_step_right = 144,
	act_step_back = 145,
	act_step_fore = 146,
	act_gesture_range_attack1 = 147,
	act_gesture_range_attack2 = 148,
	act_gesture_melee_attack1 = 149,
	act_gesture_melee_attack2 = 150,
	act_gesture_range_attack1_low = 151,
	act_gesture_range_attack2_low = 152,
	act_melee_attack_swing_gesture = 153,
	act_gesture_small_flinch = 154,
	act_gesture_big_flinch = 155,
	act_gesture_flinch_blast = 156,
	act_gesture_flinch_blast_shotgun = 157,
	act_gesture_flinch_blast_damaged = 158,
	act_gesture_flinch_blast_damaged_shotgun = 159,
	act_gesture_flinch_head = 160,
	act_gesture_flinch_chest = 161,
	act_gesture_flinch_stomach = 162,
	act_gesture_flinch_leftarm = 163,
	act_gesture_flinch_rightarm = 164,
	act_gesture_flinch_leftleg = 165,
	act_gesture_flinch_rightleg = 166,
	act_gesture_turn_left = 167,
	act_gesture_turn_right = 168,
	act_gesture_turn_left45 = 169,
	act_gesture_turn_right45 = 170,
	act_gesture_turn_left90 = 171,
	act_gesture_turn_right90 = 172,
	act_gesture_turn_left45_flat = 173,
	act_gesture_turn_right45_flat = 174,
	act_gesture_turn_left90_flat = 175,
	act_gesture_turn_right90_flat = 176,
	act_barnacle_hit = 177,
	act_barnacle_pull = 178,
	act_barnacle_chomp = 179,
	act_barnacle_chew = 180,
	act_do_not_disturb = 181,
	act_specific_sequence = 182,
	act_vm_draw = 183,
	act_vm_holster = 184,
	act_vm_idle = 185,
	act_vm_fidget = 186,
	act_vm_pullback = 187,
	act_vm_pullback_high = 188,
	act_vm_pullback_low = 189,
	act_vm_throw = 190,
	act_vm_pullpin = 191,
	act_vm_primaryattack = 192,
	act_vm_secondaryattack = 193,
	act_vm_reload = 194,
	act_vm_dryfire = 195,
	act_vm_hitleft = 196,
	act_vm_hitleft2 = 197,
	act_vm_hitright = 198,
	act_vm_hitright2 = 199,
	act_vm_hitcenter = 200,
	act_vm_hitcenter2 = 201,
	act_vm_missleft = 202,
	act_vm_missleft2 = 203,
	act_vm_missright = 204,
	act_vm_missright2 = 205,
	act_vm_misscenter = 206,
	act_vm_misscenter2 = 207,
	act_vm_haulback = 208,
	act_vm_swinghard = 209,
	act_vm_swingmiss = 210,
	act_vm_swinghit = 211,
	act_vm_idle_to_lowered = 212,
	act_vm_idle_lowered = 213,
	act_vm_lowered_to_idle = 214,
	act_vm_recoil1 = 215,
	act_vm_recoil2 = 216,
	act_vm_recoil3 = 217,
	act_vm_pickup = 218,
	act_vm_release = 219,
	act_vm_attach_silencer = 220,
	act_vm_detach_silencer = 221,
	act_vm_empty_fire = 222,
	act_vm_empty_reload = 223,
	act_vm_empty_draw = 224,
	act_vm_empty_idle = 225,
	act_slam_stickwall_idle = 226,
	act_slam_stickwall_nd_idle = 227,
	act_slam_stickwall_attach = 228,
	act_slam_stickwall_attach2 = 229,
	act_slam_stickwall_nd_attach = 230,
	act_slam_stickwall_nd_attach2 = 231,
	act_slam_stickwall_detonate = 232,
	act_slam_stickwall_detonator_holster = 233,
	act_slam_stickwall_draw = 234,
	act_slam_stickwall_nd_draw = 235,
	act_slam_stickwall_to_throw = 236,
	act_slam_stickwall_to_throw_nd = 237,
	act_slam_stickwall_to_tripmine_nd = 238,
	act_slam_throw_idle = 239,
	act_slam_throw_nd_idle = 240,
	act_slam_throw_throw = 241,
	act_slam_throw_throw2 = 242,
	act_slam_throw_throw_nd = 243,
	act_slam_throw_throw_nd2 = 244,
	act_slam_throw_draw = 245,
	act_slam_throw_nd_draw = 246,
	act_slam_throw_to_stickwall = 247,
	act_slam_throw_to_stickwall_nd = 248,
	act_slam_throw_detonate = 249,
	act_slam_throw_detonator_holster = 250,
	act_slam_throw_to_tripmine_nd = 251,
	act_slam_tripmine_idle = 252,
	act_slam_tripmine_draw = 253,
	act_slam_tripmine_attach = 254,
	act_slam_tripmine_attach2 = 255,
	act_slam_tripmine_to_stickwall_nd = 256,
	act_slam_tripmine_to_throw_nd = 257,
	act_slam_detonator_idle = 258,
	act_slam_detonator_draw = 259,
	act_slam_detonator_detonate = 260,
	act_slam_detonator_holster = 261,
	act_slam_detonator_stickwall_draw = 262,
	act_slam_detonator_throw_draw = 263,
	act_shotgun_reload_start = 264,
	act_shotgun_reload_finish = 265,
	act_shotgun_pump = 266,
	act_smg2_idle2 = 267,
	act_smg2_fire2 = 268,
	act_smg2_draw2 = 269,
	act_smg2_reload2 = 270,
	act_smg2_dryfire2 = 271,
	act_smg2_toauto = 272,
	act_smg2_toburst = 273,
	act_physcannon_upgrade = 274,
	act_range_attack_ar1 = 275,
	act_range_attack_ar2 = 276,
	act_range_attack_ar2_low = 277,
	act_range_attack_ar2_grenade = 278,
	act_range_attack_hmg1 = 279,
	act_range_attack_ml = 280,
	act_range_attack_smg1 = 281,
	act_range_attack_smg1_low = 282,
	act_range_attack_smg2 = 283,
	act_range_attack_shotgun = 284,
	act_range_attack_shotgun_low = 285,
	act_range_attack_pistol = 286,
	act_range_attack_pistol_low = 287,
	act_range_attack_slam = 288,
	act_range_attack_tripwire = 289,
	act_range_attack_throw = 290,
	act_range_attack_sniper_rifle = 291,
	act_range_attack_rpg = 292,
	act_melee_attack_swing = 293,
	act_range_aim_low = 294,
	act_range_aim_smg1_low = 295,
	act_range_aim_pistol_low = 296,
	act_range_aim_ar2_low = 297,
	act_cover_pistol_low = 298,
	act_cover_smg1_low = 299,
	act_gesture_range_attack_ar1 = 300,
	act_gesture_range_attack_ar2 = 301,
	act_gesture_range_attack_ar2_grenade = 302,
	act_gesture_range_attack_hmg1 = 303,
	act_gesture_range_attack_ml = 304,
	act_gesture_range_attack_smg1 = 305,
	act_gesture_range_attack_smg1_low = 306,
	act_gesture_range_attack_smg2 = 307,
	act_gesture_range_attack_shotgun = 308,
	act_gesture_range_attack_pistol = 309,
	act_gesture_range_attack_pistol_low = 310,
	act_gesture_range_attack_slam = 311,
	act_gesture_range_attack_tripwire = 312,
	act_gesture_range_attack_throw = 313,
	act_gesture_range_attack_sniper_rifle = 314,
	act_gesture_melee_attack_swing = 315,
	act_idle_rifle = 316,
	act_idle_smg1 = 317,
	act_idle_angry_smg1 = 318,
	act_idle_pistol = 319,
	act_idle_angry_pistol = 320,
	act_idle_angry_shotgun = 321,
	act_idle_stealth_pistol = 322,
	act_idle_package = 323,
	act_walk_package = 324,
	act_idle_suitcase = 325,
	act_walk_suitcase = 326,
	act_idle_smg1_relaxed = 327,
	act_idle_smg1_stimulated = 328,
	act_walk_rifle_relaxed = 329,
	act_run_rifle_relaxed = 330,
	act_walk_rifle_stimulated = 331,
	act_run_rifle_stimulated = 332,
	act_idle_aim_rifle_stimulated = 333,
	act_walk_aim_rifle_stimulated = 334,
	act_run_aim_rifle_stimulated = 335,
	act_idle_shotgun_relaxed = 336,
	act_idle_shotgun_stimulated = 337,
	act_idle_shotgun_agitated = 338,
	act_walk_angry = 339,
	act_police_harass1 = 340,
	act_police_harass2 = 341,
	act_idle_mannedgun = 342,
	act_idle_melee = 343,
	act_idle_angry_melee = 344,
	act_idle_rpg_relaxed = 345,
	act_idle_rpg = 346,
	act_idle_angry_rpg = 347,
	act_cover_low_rpg = 348,
	act_walk_rpg = 349,
	act_run_rpg = 350,
	act_walk_crouch_rpg = 351,
	act_run_crouch_rpg = 352,
	act_walk_rpg_relaxed = 353,
	act_run_rpg_relaxed = 354,
	act_walk_rifle = 355,
	act_walk_aim_rifle = 356,
	act_walk_crouch_rifle = 357,
	act_walk_crouch_aim_rifle = 358,
	act_run_rifle = 359,
	act_run_aim_rifle = 360,
	act_run_crouch_rifle = 361,
	act_run_crouch_aim_rifle = 362,
	act_run_stealth_pistol = 363,
	act_walk_aim_shotgun = 364,
	act_run_aim_shotgun = 365,
	act_walk_pistol = 366,
	act_run_pistol = 367,
	act_walk_aim_pistol = 368,
	act_run_aim_pistol = 369,
	act_walk_stealth_pistol = 370,
	act_walk_aim_stealth_pistol = 371,
	act_run_aim_stealth_pistol = 372,
	act_reload_pistol = 373,
	act_reload_pistol_low = 374,
	act_reload_smg1 = 375,
	act_reload_smg1_low = 376,
	act_reload_shotgun = 377,
	act_reload_shotgun_low = 378,
	act_gesture_reload = 379,
	act_gesture_reload_pistol = 380,
	act_gesture_reload_smg1 = 381,
	act_gesture_reload_shotgun = 382,
	act_busy_lean_left = 383,
	act_busy_lean_left_entry = 384,
	act_busy_lean_left_exit = 385,
	act_busy_lean_back = 386,
	act_busy_lean_back_entry = 387,
	act_busy_lean_back_exit = 388,
	act_busy_sit_ground = 389,
	act_busy_sit_ground_entry = 390,
	act_busy_sit_ground_exit = 391,
	act_busy_sit_chair = 392,
	act_busy_sit_chair_entry = 393,
	act_busy_sit_chair_exit = 394,
	act_busy_stand = 395,
	act_busy_queue = 396,
	act_duck_dodge = 397,
	act_die_barnacle_swallow = 398,
	act_gesture_barnacle_strangle = 399,
	act_physcannon_detach = 400,
	act_physcannon_animate = 401,
	act_physcannon_animate_pre = 402,
	act_physcannon_animate_post = 403,
	act_die_frontside = 404,
	act_die_rightside = 405,
	act_die_backside = 406,
	act_die_leftside = 407,
	act_die_crouch_frontside = 408,
	act_die_crouch_rightside = 409,
	act_die_crouch_backside = 410,
	act_die_crouch_leftside = 411,
	act_open_door = 412,
	act_di_alyx_zombie_melee = 413,
	act_di_alyx_zombie_torso_melee = 414,
	act_di_alyx_headcrab_melee = 415,
	act_di_alyx_antlion = 416,
	act_di_alyx_zombie_shotgun64 = 417,
	act_di_alyx_zombie_shotgun26 = 418,
	act_readiness_relaxed_to_stimulated = 419,
	act_readiness_relaxed_to_stimulated_walk = 420,
	act_readiness_agitated_to_stimulated = 421,
	act_readiness_stimulated_to_relaxed = 422,
	act_readiness_pistol_relaxed_to_stimulated = 423,
	act_readiness_pistol_relaxed_to_stimulated_walk = 424,
	act_readiness_pistol_agitated_to_stimulated = 425,
	act_readiness_pistol_stimulated_to_relaxed = 426,
	act_idle_carry = 427,
	act_walk_carry = 428,
	act_startdying = 429,
	act_dyingloop = 430,
	act_dyingtodead = 431,
	act_ride_manned_gun = 432,
	act_vm_sprint_enter = 433,
	act_vm_sprint_idle = 434,
	act_vm_sprint_leave = 435,
	act_fire_start = 436,
	act_fire_loop = 437,
	act_fire_end = 438,
	act_crouching_grenadeidle = 439,
	act_crouching_grenadeready = 440,
	act_crouching_primaryattack = 441,
	act_overlay_grenadeidle = 442,
	act_overlay_grenadeready = 443,
	act_overlay_primaryattack = 444,
	act_overlay_shield_up = 445,
	act_overlay_shield_down = 446,
	act_overlay_shield_up_idle = 447,
	act_overlay_shield_attack = 448,
	act_overlay_shield_knockback = 449,
	act_shield_up = 450,
	act_shield_down = 451,
	act_shield_up_idle = 452,
	act_shield_attack = 453,
	act_shield_knockback = 454,
	act_crouching_shield_up = 455,
	act_crouching_shield_down = 456,
	act_crouching_shield_up_idle = 457,
	act_crouching_shield_attack = 458,
	act_crouching_shield_knockback = 459,
	act_turnright45 = 460,
	act_turnleft45 = 461,
	act_turn = 462,
	act_obj_assembling = 463,
	act_obj_dismantling = 464,
	act_obj_startup = 465,
	act_obj_running = 466,
	act_obj_idle = 467,
	act_obj_placing = 468,
	act_obj_deteriorating = 469,
	act_obj_upgrading = 470,
	act_deploy = 471,
	act_deploy_idle = 472,
	act_undeploy = 473,
	act_crossbow_draw_unloaded = 474,
	act_gauss_spinup = 475,
	act_gauss_spincycle = 476,
	act_vm_primaryattack_silenced = 477,
	act_vm_reload_silenced = 478,
	act_vm_dryfire_silenced = 479,
	act_vm_idle_silenced = 480,
	act_vm_draw_silenced = 481,
	act_vm_idle_empty_left = 482,
	act_vm_dryfire_left = 483,
	act_vm_is_draw = 484,
	act_vm_is_holster = 485,
	act_vm_is_idle = 486,
	act_vm_is_primaryattack = 487,
	act_player_idle_fire = 488,
	act_player_crouch_fire = 489,
	act_player_crouch_walk_fire = 490,
	act_player_walk_fire = 491,
	act_player_run_fire = 492,
	act_idletorun = 493,
	act_runtoidle = 494,
	act_vm_draw_deployed = 495,
	act_hl2mp_idle_melee = 496,
	act_hl2mp_run_melee = 497,
	act_hl2mp_idle_crouch_melee = 498,
	act_hl2mp_walk_crouch_melee = 499,
	act_hl2mp_gesture_range_attack_melee = 500,
	act_hl2mp_gesture_reload_melee = 501,
	act_hl2mp_jump_melee = 502,
	act_vm_fizzle = 503,
	act_mp_stand_idle = 504,
	act_mp_crouch_idle = 505,
	act_mp_crouch_deployed_idle = 506,
	act_mp_crouch_deployed = 507,
	act_mp_deployed_idle = 508,
	act_mp_run = 509,
	act_mp_walk = 510,
	act_mp_airwalk = 511,
	act_mp_crouchwalk = 512,
	act_mp_sprint = 513,
	act_mp_jump = 514,
	act_mp_jump_start = 515,
	act_mp_jump_float = 516,
	act_mp_jump_land = 517,
	act_mp_jump_impact_n = 518,
	act_mp_jump_impact_e = 519,
	act_mp_jump_impact_w = 520,
	act_mp_jump_impact_s = 521,
	act_mp_jump_impact_top = 522,
	act_mp_doublejump = 523,
	act_mp_swim = 524,
	act_mp_deployed = 525,
	act_mp_swim_deployed = 526,
	act_mp_vcd = 527,
	act_mp_attack_stand_primaryfire = 528,
	act_mp_attack_stand_primaryfire_deployed = 529,
	act_mp_attack_stand_secondaryfire = 530,
	act_mp_attack_stand_grenade = 531,
	act_mp_attack_crouch_primaryfire = 532,
	act_mp_attack_crouch_primaryfire_deployed = 533,
	act_mp_attack_crouch_secondaryfire = 534,
	act_mp_attack_crouch_grenade = 535,
	act_mp_attack_swim_primaryfire = 536,
	act_mp_attack_swim_secondaryfire = 537,
	act_mp_attack_swim_grenade = 538,
	act_mp_attack_airwalk_primaryfire = 539,
	act_mp_attack_airwalk_secondaryfire = 540,
	act_mp_attack_airwalk_grenade = 541,
	act_mp_reload_stand = 542,
	act_mp_reload_stand_loop = 543,
	act_mp_reload_stand_end = 544,
	act_mp_reload_crouch = 545,
	act_mp_reload_crouch_loop = 546,
	act_mp_reload_crouch_end = 547,
	act_mp_reload_swim = 548,
	act_mp_reload_swim_loop = 549,
	act_mp_reload_swim_end = 550,
	act_mp_reload_airwalk = 551,
	act_mp_reload_airwalk_loop = 552,
	act_mp_reload_airwalk_end = 553,
	act_mp_attack_stand_prefire = 554,
	act_mp_attack_stand_postfire = 555,
	act_mp_attack_stand_startfire = 556,
	act_mp_attack_crouch_prefire = 557,
	act_mp_attack_crouch_postfire = 558,
	act_mp_attack_swim_prefire = 559,
	act_mp_attack_swim_postfire = 560,
	act_mp_stand_primary = 561,
	act_mp_crouch_primary = 562,
	act_mp_run_primary = 563,
	act_mp_walk_primary = 564,
	act_mp_airwalk_primary = 565,
	act_mp_crouchwalk_primary = 566,
	act_mp_jump_primary = 567,
	act_mp_jump_start_primary = 568,
	act_mp_jump_float_primary = 569,
	act_mp_jump_land_primary = 570,
	act_mp_swim_primary = 571,
	act_mp_deployed_primary = 572,
	act_mp_swim_deployed_primary = 573,
	act_mp_attack_stand_primary = 574,
	act_mp_attack_stand_primary_deployed = 575,
	act_mp_attack_crouch_primary = 576,
	act_mp_attack_crouch_primary_deployed = 577,
	act_mp_attack_swim_primary = 578,
	act_mp_attack_airwalk_primary = 579,
	act_mp_reload_stand_primary = 580,
	act_mp_reload_stand_primary_loop = 581,
	act_mp_reload_stand_primary_end = 582,
	act_mp_reload_crouch_primary = 583,
	act_mp_reload_crouch_primary_loop = 584,
	act_mp_reload_crouch_primary_end = 585,
	act_mp_reload_swim_primary = 586,
	act_mp_reload_swim_primary_loop = 587,
	act_mp_reload_swim_primary_end = 588,
	act_mp_reload_airwalk_primary = 589,
	act_mp_reload_airwalk_primary_loop = 590,
	act_mp_reload_airwalk_primary_end = 591,
	act_mp_attack_stand_grenade_primary = 592,
	act_mp_attack_crouch_grenade_primary = 593,
	act_mp_attack_swim_grenade_primary = 594,
	act_mp_attack_airwalk_grenade_primary = 595,
	act_mp_stand_secondary = 596,
	act_mp_crouch_secondary = 597,
	act_mp_run_secondary = 598,
	act_mp_walk_secondary = 599,
	act_mp_airwalk_secondary = 600,
	act_mp_crouchwalk_secondary = 601,
	act_mp_jump_secondary = 602,
	act_mp_jump_start_secondary = 603,
	act_mp_jump_float_secondary = 604,
	act_mp_jump_land_secondary = 605,
	act_mp_swim_secondary = 606,
	act_mp_attack_stand_secondary = 607,
	act_mp_attack_crouch_secondary = 608,
	act_mp_attack_swim_secondary = 609,
	act_mp_attack_airwalk_secondary = 610,
	act_mp_reload_stand_secondary = 611,
	act_mp_reload_stand_secondary_loop = 612,
	act_mp_reload_stand_secondary_end = 613,
	act_mp_reload_crouch_secondary = 614,
	act_mp_reload_crouch_secondary_loop = 615,
	act_mp_reload_crouch_secondary_end = 616,
	act_mp_reload_swim_secondary = 617,
	act_mp_reload_swim_secondary_loop = 618,
	act_mp_reload_swim_secondary_end = 619,
	act_mp_reload_airwalk_secondary = 620,
	act_mp_reload_airwalk_secondary_loop = 621,
	act_mp_reload_airwalk_secondary_end = 622,
	act_mp_attack_stand_grenade_secondary = 623,
	act_mp_attack_crouch_grenade_secondary = 624,
	act_mp_attack_swim_grenade_secondary = 625,
	act_mp_attack_airwalk_grenade_secondary = 626,
	act_mp_stand_melee = 627,
	act_mp_crouch_melee = 628,
	act_mp_run_melee = 629,
	act_mp_walk_melee = 630,
	act_mp_airwalk_melee = 631,
	act_mp_crouchwalk_melee = 632,
	act_mp_jump_melee = 633,
	act_mp_jump_start_melee = 634,
	act_mp_jump_float_melee = 635,
	act_mp_jump_land_melee = 636,
	act_mp_swim_melee = 637,
	act_mp_attack_stand_melee = 638,
	act_mp_attack_stand_melee_secondary = 639,
	act_mp_attack_crouch_melee = 640,
	act_mp_attack_crouch_melee_secondary = 641,
	act_mp_attack_swim_melee = 642,
	act_mp_attack_airwalk_melee = 643,
	act_mp_attack_stand_grenade_melee = 644,
	act_mp_attack_crouch_grenade_melee = 645,
	act_mp_attack_swim_grenade_melee = 646,
	act_mp_attack_airwalk_grenade_melee = 647,
	act_mp_stand_item1 = 648,
	act_mp_crouch_item1 = 649,
	act_mp_run_item1 = 650,
	act_mp_walk_item1 = 651,
	act_mp_airwalk_item1 = 652,
	act_mp_crouchwalk_item1 = 653,
	act_mp_jump_item1 = 654,
	act_mp_jump_start_item1 = 655,
	act_mp_jump_float_item1 = 656,
	act_mp_jump_land_item1 = 657,
	act_mp_swim_item1 = 658,
	act_mp_attack_stand_item1 = 659,
	act_mp_attack_stand_item1_secondary = 660,
	act_mp_attack_crouch_item1 = 661,
	act_mp_attack_crouch_item1_secondary = 662,
	act_mp_attack_swim_item1 = 663,
	act_mp_attack_airwalk_item1 = 664,
	act_mp_stand_item2 = 665,
	act_mp_crouch_item2 = 666,
	act_mp_run_item2 = 667,
	act_mp_walk_item2 = 668,
	act_mp_airwalk_item2 = 669,
	act_mp_crouchwalk_item2 = 670,
	act_mp_jump_item2 = 671,
	act_mp_jump_start_item2 = 672,
	act_mp_jump_float_item2 = 673,
	act_mp_jump_land_item2 = 674,
	act_mp_swim_item2 = 675,
	act_mp_attack_stand_item2 = 676,
	act_mp_attack_stand_item2_secondary = 677,
	act_mp_attack_crouch_item2 = 678,
	act_mp_attack_crouch_item2_secondary = 679,
	act_mp_attack_swim_item2 = 680,
	act_mp_attack_airwalk_item2 = 681,
	act_mp_gesture_flinch = 682,
	act_mp_gesture_flinch_primary = 683,
	act_mp_gesture_flinch_secondary = 684,
	act_mp_gesture_flinch_melee = 685,
	act_mp_gesture_flinch_item1 = 686,
	act_mp_gesture_flinch_item2 = 687,
	act_mp_gesture_flinch_head = 688,
	act_mp_gesture_flinch_chest = 689,
	act_mp_gesture_flinch_stomach = 690,
	act_mp_gesture_flinch_leftarm = 691,
	act_mp_gesture_flinch_rightarm = 692,
	act_mp_gesture_flinch_leftleg = 693,
	act_mp_gesture_flinch_rightleg = 694,
	act_mp_grenade1_draw = 695,
	act_mp_grenade1_idle = 696,
	act_mp_grenade1_attack = 697,
	act_mp_grenade2_draw = 698,
	act_mp_grenade2_idle = 699,
	act_mp_grenade2_attack = 700,
	act_mp_primary_grenade1_draw = 701,
	act_mp_primary_grenade1_idle = 702,
	act_mp_primary_grenade1_attack = 703,
	act_mp_primary_grenade2_draw = 704,
	act_mp_primary_grenade2_idle = 705,
	act_mp_primary_grenade2_attack = 706,
	act_mp_secondary_grenade1_draw = 707,
	act_mp_secondary_grenade1_idle = 708,
	act_mp_secondary_grenade1_attack = 709,
	act_mp_secondary_grenade2_draw = 710,
	act_mp_secondary_grenade2_idle = 711,
	act_mp_secondary_grenade2_attack = 712,
	act_mp_melee_grenade1_draw = 713,
	act_mp_melee_grenade1_idle = 714,
	act_mp_melee_grenade1_attack = 715,
	act_mp_melee_grenade2_draw = 716,
	act_mp_melee_grenade2_idle = 717,
	act_mp_melee_grenade2_attack = 718,
	act_mp_item1_grenade1_draw = 719,
	act_mp_item1_grenade1_idle = 720,
	act_mp_item1_grenade1_attack = 721,
	act_mp_item1_grenade2_draw = 722,
	act_mp_item1_grenade2_idle = 723,
	act_mp_item1_grenade2_attack = 724,
	act_mp_item2_grenade1_draw = 725,
	act_mp_item2_grenade1_idle = 726,
	act_mp_item2_grenade1_attack = 727,
	act_mp_item2_grenade2_draw = 728,
	act_mp_item2_grenade2_idle = 729,
	act_mp_item2_grenade2_attack = 730,
	act_mp_stand_building = 731,
	act_mp_crouch_building = 732,
	act_mp_run_building = 733,
	act_mp_walk_building = 734,
	act_mp_airwalk_building = 735,
	act_mp_crouchwalk_building = 736,
	act_mp_jump_building = 737,
	act_mp_jump_start_building = 738,
	act_mp_jump_float_building = 739,
	act_mp_jump_land_building = 740,
	act_mp_swim_building = 741,
	act_mp_attack_stand_building = 742,
	act_mp_attack_crouch_building = 743,
	act_mp_attack_swim_building = 744,
	act_mp_attack_airwalk_building = 745,
	act_mp_attack_stand_grenade_building = 746,
	act_mp_attack_crouch_grenade_building = 747,
	act_mp_attack_swim_grenade_building = 748,
	act_mp_attack_airwalk_grenade_building = 749,
	act_mp_stand_pda = 750,
	act_mp_crouch_pda = 751,
	act_mp_run_pda = 752,
	act_mp_walk_pda = 753,
	act_mp_airwalk_pda = 754,
	act_mp_crouchwalk_pda = 755,
	act_mp_jump_pda = 756,
	act_mp_jump_start_pda = 757,
	act_mp_jump_float_pda = 758,
	act_mp_jump_land_pda = 759,
	act_mp_swim_pda = 760,
	act_mp_attack_stand_pda = 761,
	act_mp_attack_swim_pda = 762,
	act_mp_gesture_vc_handmouth = 763,
	act_mp_gesture_vc_fingerpoint = 764,
	act_mp_gesture_vc_fistpump = 765,
	act_mp_gesture_vc_thumbsup = 766,
	act_mp_gesture_vc_nodyes = 767,
	act_mp_gesture_vc_nodno = 768,
	act_mp_gesture_vc_handmouth_primary = 769,
	act_mp_gesture_vc_fingerpoint_primary = 770,
	act_mp_gesture_vc_fistpump_primary = 771,
	act_mp_gesture_vc_thumbsup_primary = 772,
	act_mp_gesture_vc_nodyes_primary = 773,
	act_mp_gesture_vc_nodno_primary = 774,
	act_mp_gesture_vc_handmouth_secondary = 775,
	act_mp_gesture_vc_fingerpoint_secondary = 776,
	act_mp_gesture_vc_fistpump_secondary = 777,
	act_mp_gesture_vc_thumbsup_secondary = 778,
	act_mp_gesture_vc_nodyes_secondary = 779,
	act_mp_gesture_vc_nodno_secondary = 780,
	act_mp_gesture_vc_handmouth_melee = 781,
	act_mp_gesture_vc_fingerpoint_melee = 782,
	act_mp_gesture_vc_fistpump_melee = 783,
	act_mp_gesture_vc_thumbsup_melee = 784,
	act_mp_gesture_vc_nodyes_melee = 785,
	act_mp_gesture_vc_nodno_melee = 786,
	act_mp_gesture_vc_handmouth_item1 = 787,
	act_mp_gesture_vc_fingerpoint_item1 = 788,
	act_mp_gesture_vc_fistpump_item1 = 789,
	act_mp_gesture_vc_thumbsup_item1 = 790,
	act_mp_gesture_vc_nodyes_item1 = 791,
	act_mp_gesture_vc_nodno_item1 = 792,
	act_mp_gesture_vc_handmouth_item2 = 793,
	act_mp_gesture_vc_fingerpoint_item2 = 794,
	act_mp_gesture_vc_fistpump_item2 = 795,
	act_mp_gesture_vc_thumbsup_item2 = 796,
	act_mp_gesture_vc_nodyes_item2 = 797,
	act_mp_gesture_vc_nodno_item2 = 798,
	act_mp_gesture_vc_handmouth_building = 799,
	act_mp_gesture_vc_fingerpoint_building = 800,
	act_mp_gesture_vc_fistpump_building = 801,
	act_mp_gesture_vc_thumbsup_building = 802,
	act_mp_gesture_vc_nodyes_building = 803,
	act_mp_gesture_vc_nodno_building = 804,
	act_mp_gesture_vc_handmouth_pda = 805,
	act_mp_gesture_vc_fingerpoint_pda = 806,
	act_mp_gesture_vc_fistpump_pda = 807,
	act_mp_gesture_vc_thumbsup_pda = 808,
	act_mp_gesture_vc_nodyes_pda = 809,
	act_mp_gesture_vc_nodno_pda = 810,
	act_vm_unusable = 811,
	act_vm_unusable_to_usable = 812,
	act_vm_usable_to_unusable = 813,
	act_primary_vm_draw = 814,
	act_primary_vm_holster = 815,
	act_primary_vm_idle = 816,
	act_primary_vm_pullback = 817,
	act_primary_vm_primaryattack = 818,
	act_primary_vm_secondaryattack = 819,
	act_primary_vm_reload = 820,
	act_primary_vm_dryfire = 821,
	act_primary_vm_idle_to_lowered = 822,
	act_primary_vm_idle_lowered = 823,
	act_primary_vm_lowered_to_idle = 824,
	act_secondary_vm_draw = 825,
	act_secondary_vm_holster = 826,
	act_secondary_vm_idle = 827,
	act_secondary_vm_pullback = 828,
	act_secondary_vm_primaryattack = 829,
	act_secondary_vm_secondaryattack = 830,
	act_secondary_vm_reload = 831,
	act_secondary_vm_dryfire = 832,
	act_secondary_vm_idle_to_lowered = 833,
	act_secondary_vm_idle_lowered = 834,
	act_secondary_vm_lowered_to_idle = 835,
	act_melee_vm_draw = 836,
	act_melee_vm_holster = 837,
	act_melee_vm_idle = 838,
	act_melee_vm_pullback = 839,
	act_melee_vm_primaryattack = 840,
	act_melee_vm_secondaryattack = 841,
	act_melee_vm_reload = 842,
	act_melee_vm_dryfire = 843,
	act_melee_vm_idle_to_lowered = 844,
	act_melee_vm_idle_lowered = 845,
	act_melee_vm_lowered_to_idle = 846,
	act_pda_vm_draw = 847,
	act_pda_vm_holster = 848,
	act_pda_vm_idle = 849,
	act_pda_vm_pullback = 850,
	act_pda_vm_primaryattack = 851,
	act_pda_vm_secondaryattack = 852,
	act_pda_vm_reload = 853,
	act_pda_vm_dryfire = 854,
	act_pda_vm_idle_to_lowered = 855,
	act_pda_vm_idle_lowered = 856,
	act_pda_vm_lowered_to_idle = 857,
	act_item1_vm_draw = 858,
	act_item1_vm_holster = 859,
	act_item1_vm_idle = 860,
	act_item1_vm_pullback = 861,
	act_item1_vm_primaryattack = 862,
	act_item1_vm_secondaryattack = 863,
	act_item1_vm_reload = 864,
	act_item1_vm_dryfire = 865,
	act_item1_vm_idle_to_lowered = 866,
	act_item1_vm_idle_lowered = 867,
	act_item1_vm_lowered_to_idle = 868,
	act_item2_vm_draw = 869,
	act_item2_vm_holster = 870,
	act_item2_vm_idle = 871,
	act_item2_vm_pullback = 872,
	act_item2_vm_primaryattack = 873,
	act_item2_vm_secondaryattack = 874,
	act_item2_vm_reload = 875,
	act_item2_vm_dryfire = 876,
	act_item2_vm_idle_to_lowered = 877,
	act_item2_vm_idle_lowered = 878,
	act_item2_vm_lowered_to_idle = 879,
	act_reload_succeed = 880,
	act_reload_fail = 881,
	act_walk_aim_autogun = 882,
	act_run_aim_autogun = 883,
	act_idle_autogun = 884,
	act_idle_aim_autogun = 885,
	act_reload_autogun = 886,
	act_crouch_idle_autogun = 887,
	act_range_attack_autogun = 888,
	act_jump_autogun = 889,
	act_idle_aim_pistol = 890,
	act_walk_aim_dual = 891,
	act_run_aim_dual = 892,
	act_idle_dual = 893,
	act_idle_aim_dual = 894,
	act_reload_dual = 895,
	act_crouch_idle_dual = 896,
	act_range_attack_dual = 897,
	act_jump_dual = 898,
	act_idle_shotgun = 899,
	act_idle_aim_shotgun = 900,
	act_crouch_idle_shotgun = 901,
	act_jump_shotgun = 902,
	act_idle_aim_rifle = 903,
	act_reload_rifle = 904,
	act_crouch_idle_rifle = 905,
	act_range_attack_rifle = 906,
	act_jump_rifle = 907,
	act_sleep = 908,
	act_wake = 909,
	act_flick_left = 910,
	act_flick_left_middle = 911,
	act_flick_right_middle = 912,
	act_flick_right = 913,
	act_spinaround = 914,
	act_prep_to_fire = 915,
	act_fire = 916,
	act_fire_recover = 917,
	act_spray = 918,
	act_prep_explode = 919,
	act_explode = 920,
	act_dota_idle = 921,
	act_dota_run = 922,
	act_dota_attack = 923,
	act_dota_attack_event = 924,
	act_dota_die = 925,
	act_dota_flinch = 926,
	act_dota_disabled = 927,
	act_dota_cast_ability_1 = 928,
	act_dota_cast_ability_2 = 929,
	act_dota_cast_ability_3 = 930,
	act_dota_cast_ability_4 = 931,
	act_dota_override_ability_1 = 932,
	act_dota_override_ability_2 = 933,
	act_dota_override_ability_3 = 934,
	act_dota_override_ability_4 = 935,
	act_dota_channel_ability_1 = 936,
	act_dota_channel_ability_2 = 937,
	act_dota_channel_ability_3 = 938,
	act_dota_channel_ability_4 = 939,
	act_dota_channel_end_ability_1 = 940,
	act_dota_channel_end_ability_2 = 941,
	act_dota_channel_end_ability_3 = 942,
	act_dota_channel_end_ability_4 = 943,
	act_mp_run_speedpaint = 944,
	act_mp_long_fall = 945,
	act_mp_tractorbeam_float = 946,
	act_mp_death_crush = 947,
	act_mp_run_speedpaint_primary = 948,
	act_mp_drowning_primary = 949,
	act_mp_long_fall_primary = 950,
	act_mp_tractorbeam_float_primary = 951,
	act_mp_death_crush_primary = 952,
	act_die_stand = 953,
	act_die_stand_headshot = 954,
	act_die_crouch = 955,
	act_die_crouch_headshot = 956,
	act_csgo_null = 957,
	act_csgo_defuse = 958,
	act_csgo_defuse_with_kit = 959,
	act_csgo_flashbang_reaction = 960,
	act_csgo_fire_primary = 961,
	act_csgo_fire_primary_opt_1 = 962,
	act_csgo_fire_primary_opt_2 = 963,
	act_csgo_fire_secondary = 964,
	act_csgo_fire_secondary_opt_1 = 965,
	act_csgo_fire_secondary_opt_2 = 966,
	act_csgo_reload = 967,
	act_csgo_reload_start = 968,
	act_csgo_reload_loop = 969,
	act_csgo_reload_end = 970,
	act_csgo_operate = 971,
	act_csgo_deploy = 972,
	act_csgo_catch = 973,
	act_csgo_silencer_detach = 974,
	act_csgo_silencer_attach = 975,
	act_csgo_twitch = 976,
	act_csgo_twitch_buyzone = 977,
	act_csgo_plant_bomb = 978,
	act_csgo_idle_turn_balanceadjust = 979,
	act_csgo_idle_adjust_stoppedmoving = 980,
	act_csgo_alive_loop = 981,
	act_csgo_flinch = 982,
	act_csgo_flinch_head = 983,
	act_csgo_flinch_molotov = 984,
	act_csgo_jump = 985,
	act_csgo_fall = 986,
	act_csgo_climb_ladder = 987,
	act_csgo_land_light = 988,
	act_csgo_land_heavy = 989,
	act_csgo_exit_ladder_top = 990,
	act_csgo_exit_ladder_bottom = 991,
	act_csgo_parachute = 992,
	act_csgo_uiplayer_idle = 993,
	act_csgo_uiplayer_walkup = 994,
	act_csgo_uiplayer_celebrate = 995,
	act_csgo_uiplayer_confirm = 996,
	act_csgo_uiplayer_buymenu = 997,
	act_csgo_uiplayer_patch = 998,
	activity_list_max
};

enum e_image_format
{
	image_format_unknown = -1,
	image_format_rgba8888 = 0,
	image_format_abgr8888,
	image_format_rgb888,
	image_format_bgr888,
	image_format_rgb565,
	image_format_i8,
	image_format_ia88,
	image_format_p8,
	image_format_a8,
	image_format_rgb888_bluescreen,
	image_format_bgr888_bluescreen,
	image_format_argb8888,
	image_format_bgra8888,
	image_format_dxt1,
	image_format_dxt3,
	image_format_dxt5,
	image_format_bgrx8888,
	image_format_bgr565,
	image_format_bgrx5551,
	image_format_bgra4444,
	image_format_dxt1_onebitalpha,
	image_format_bgra5551,
	image_format_uv88,
	image_format_uvwq8888,
	image_format_rgba16161616f,
	image_format_rgba16161616,
	image_format_uvlx8888,
	image_format_r32f,
	image_format_rgb323232f,
	image_format_rgba32323232f,
	image_format_nv_dst16,
	image_format_nv_dst24,
	image_format_nv_intz,
	image_format_nv_rawz,
	image_format_ati_dst16,
	image_format_ati_dst24,
	image_format_nv_null,
	image_format_ati2n,
	image_format_ati1n,
	image_format_dxt1_runtime,
	image_format_dxt5_runtime,
	num_image_formats
};